# vtsls config
[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.typescript-language-server.config.typescript]
updateImportsOnFileMove.enabled = "always"
suggest.completeFunctionCalls = true
tsserver.enableTracing = true
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes = true
inlayHints.enumMemberValues.enabled = true
format.enable = false
format.semicolons = "remove"
preferences.importModuleSpecifier = "non-relative"
preferences.importModuleSpecifierEnding = "auto"

# tsgo config
[language-server.tsgo]
command = "tsgo"
args = ["--lsp", "--stdio"]

[language-server.tsgo.config.typescript]
updateImportsOnFileMove.enabled = "always"
suggest.completeFunctionCalls = true
tsserver.enableTracing = true
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes = true
inlayHints.enumMemberValues.enabled = true
format.enable = false
tsserver.experimental.enableProjectDiagnostics = true

# efm config (mostly for eslint compat)
[language-server.efm-eslint]
# See: https://github.com/mattn/efm-langserver/blob/master/schema.md#languages_pattern1
# And: https://github.com/mattn/efm-langserver?tab=readme-ov-file#example-for-configyaml
command = "efm-langserver"

[language-server.efm-eslint.config]
# Sent to efm-langserver at startup to configure it. 🎉
# See: https://github.com/mattn/efm-langserver?tab=readme-ov-file#initializeparams
documentFormatting = true
documentRangeFormatting = true
hover = true
documentSymbol = true
codeAction = true
completion = true

[[language-server.efm-eslint.config.languages.angular]]
lintCommand = "eslint --stdin --stdin-filename ${INPUT}"
lintStdin = true
lintIgnoreExitCode = true
lintAfterOpen = true
lintFormats = [
   # Very helpful examples. Need to parse multi-line messages where file only appears once:
   # See: https://vimhelp.org/quickfix.txt.html#errorformats
   # And: https://reviewdog.github.io/errorformat-playground/
   "%+P%f", # a file-like string on a single line.
   "%*[ ]%l:%c%*[ ]%t%*[^ ]%*[ ]%m",
   "%-O", # if not a match, pop filename from %P stack.

   # Example eslint output:
   #
   # /full/path/to/your/source.file.ts
   #    16:1  error    There should be no empty line within import group  import/order
   #   472:1  warning  Missing return type on function                    @typescript-eslint/explicit-function-return-type
   #   479:3  warning  Missing return type on function                    @typescript-eslint/explicit-function-return-type
]

[[language-server.efm-eslint.config.languages.typescript]]
lintCommand = "eslint --stdin --stdin-filename ${INPUT}"
lintStdin = true
lintIgnoreExitCode = true
lintAfterOpen = true
lintFormats = [
   # Very helpful examples. Need to parse multi-line messages where file only appears once:
   # See: https://vimhelp.org/quickfix.txt.html#errorformats
   # And: https://reviewdog.github.io/errorformat-playground/
   "%+P%f", # a file-like string on a single line.
   "%*[ ]%l:%c%*[ ]%t%*[^ ]%*[ ]%m",
   "%-O", # if not a match, pop filename from %P stack.

   # Example eslint output:
   #
   # /full/path/to/your/source.file.ts
   #    16:1  error    There should be no empty line within import group  import/order
   #   472:1  warning  Missing return type on function                    @typescript-eslint/explicit-function-return-type
   #   479:3  warning  Missing return type on function                    @typescript-eslint/explicit-function-return-type
]

# go config
[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
# diagnosticsTrigger = "Save"
usePlaceholders = true
staticcheck = true
vulncheck = "Imports" # or "All"
gofumpt = true

[language-server.gopls.config.analyses]
unusedfunc = true
unusedparams = true
unreachable = true
unusedvariable = true

[language-server.gopls.config.hints]
compositeLiteralTypes = true



# Frontend Language Config
[[language]]
name = "angular"
scope = "source.angular"
injection-regex = "html"
file-types = ["component.html", "html"] # Angular 21+ updated the naming format
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [{name = "efm-eslint", only-features = [ "diagnostics", "format" ]}, "angular"]
roots = ["project.json"]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true
[language.auto-pairs]
'(' = ')'
'{' = '}'
'"' = '"'
"'" = "'"

[[grammar]]
name = "angular"
source = { git = "https://github.com/dlvandenberg/tree-sitter-angular", rev = "f0d0685701b70883fa2dfe94ee7dc27965cab841" }

[[language]]
name = "typescript"
auto-format = true
language-servers = [
   "angular",
   { name = "tsgo", except-features = ["format", "completion", "code-action", "goto-reference"] }, # Angular handles file references
   { name = "typescript-language-server", only-features = ["completion", "code-action", "workspace-command"] },
   { name = "efm-eslint", only-features = [ "diagnostics", "format"]}
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
roots = ["package.json"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "babel"] }
roots = ["package.json"]

[[language]]
name = "scss"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "scss"] }
roots = ["package.json"]

[[language]]
name = "json"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "json"] }
roots = ["package.json"]

# Backend Language Config
[[language]]
name = "go"
indent = { tab-width = 2, unit = " " }
auto-format = true
language-servers = ["gopls"]
formatter = { command = "gofumpt" }

